name: CI
on:
  push:
    branches: [ releases ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Runchecksyntax
      run: |
        cd gsp_demo_java/src/main/java/demos/checksyntax
        compile_checksyntax.bat
        run_checksyntax.bat
    - name: Rungettablecolumns
      run: |
        cd gsp_demo_java/src/main/java/demos/gettablecolumns
        compile_gettablecolumns.bat
        run_runGetTableColumns.bat
        
